'use client'
import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import MobileNav from '@/components/MobileNav'
import DesktopNav from '@/components/DesktopNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} id="body-wrapper">
        <MobileNav
          pageWrapperId="page-wrapper"
          outerContainerId="body-wrapper"
          className="block md:hidden"
        />
        <Header />
        <DesktopNav />
        <main id="page-wrapper">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
